### ISSUE TITLE
compile error 'Decoders' in namespace 'Eloquent::Vision::IO' does not name a type

### ISSUE THREAD

**Issue by deepakrkpa** [eloquentarduino/EloquentArduino#20]
I am getting below error while compiling the above code in Arduino IDE :
error: 'Decoders' in namespace 'Eloquent::Vision::IO' does not name a type

 IO::Decoders::Red565RandomAccessDecoder decoder;

I am using the RGB version of code and try to compile it.

**Comment by eloquentarduino** [comment]
If you're referring to the tutorial (https://eloquentarduino.github.io/2021/01/esp32-cam-motion-detection-with-photo-capture-rgb-version/)[https://eloquentarduino.github.io/2021/01/esp32-cam-motion-detection-with-photo-capture-rgb-version/], then you're missing (because it's missing from the tutorial)

```cpp
#include <eloquentarduino/vision/io/decoders/Red565RandomAccessDecoder.h>
```

I fixed the tutorial.
Is it working now?
