### ISSUE TITLE
compilation problem

### ISSUE THREAD

**Issue by xiaocao666tzh** [eloquentarduino/EloquentArduino#21]
Dear man:
    After I recorded the sound data and train them, I use micromlgen to output a "model.h" file. But when I include it to my project file and try to compile it, I found the "cstdarg.h" is missing. I changed it to "stdarg.h" and compiled again, it come out a error:  'predict' was not declared in this scope.
Is there anything wrong?

**Comment by eloquentarduino** [comment]
Ok, you're reading an old blog post, the code changed. Here it is.

```cpp
#include <arduinoFFT.h>
// uncomment when doing classification
#include "model.h.cpp"
#define MIC A0
#define NUM_SAMPLES 64
#define SAMPLING_FREQUENCY 1024
#define INTERVAL 5
#define SOUND_THRESHOLD 3

unsigned int samplingPeriod;
unsigned long microSeconds;

int32_t backgroundSound;
double features[NUM_SAMPLES];
arduinoFFT fft;

// add this
Eloquent::ML::Port::RandomForest classifier;

void setup() {
    Serial.begin(115200);
    pinMode(MIC, INPUT);

    samplingPeriod = round(1000000*(1.0/SAMPLING_FREQUENCY));
    calibrate();

}

void loop() {
    if (!soundDetected()) {
        delay(10);
        return;
    }

    captureWord();
    printFeatures();

// uncomment when doing classification
    Serial.print("You said ");
    // replace this
    Serial.println(classifier.predictLabel(features));

    delay(1000);

}

/**

    Get analog readings
    @return
    */
int16_t readMic() {
    return analogRead(MIC);
    return (analogRead(MIC) - 512) >> 2;
}

/**

    Get "ambient" volume
    */
void calibrate() {
    for (int i = 0; i < 200; i++)
        backgroundSound += readMic();

    backgroundSound /= 200;

    Serial.print("Threshold set at ");
    Serial.println(backgroundSound);
}

bool soundDetected() {
    return abs(readMic() - backgroundSound) >= SOUND_THRESHOLD;
}

void captureWord() {
    for (uint16_t i = 0; i < NUM_SAMPLES; i++) {
        microSeconds = micros();
        features[i] = readMic();

        while(micros() < (microSeconds + samplingPeriod));
    }

    fft.Windowing(features, NUM_SAMPLES, FFT_WIN_TYP_HAMMING, FFT_FORWARD);

}

void printFeatures() {
    const uint16_t numFeatures = sizeof(features) / sizeof(double);

    for (int i = 0; i < numFeatures; i++) {
        Serial.print(features[i]);
        Serial.print(i == numFeatures - 1 ? '\n' : ',');
    }

}
```

Modifications at:

 1. line 18: create classifier instance
 2. line 40: predict class label

**Comment by eloquentarduino** [comment]
Again, as is now, the classifier will always print "shang1": you have to train it on more that one word, or in your case, train on "shang1" vs "everything but shang1"

**Comment by pigener** [comment]
It's very kind of you! I'll try.
Actualy we want to spot an animal sound from wild environment, helping to find the animals(for example wolf). So we only need some animal sound samples in vary background noises and train them, Is that right?
Could we talk in twitter or telegram if we have some more questions?

**Comment by eloquentarduino** [comment]
You will actually need any possible sound that may happen where you're going to deploy your system. Will you deploy in a forest? Go into a forest and record the birds, the wind, the woods, other animals and so on.
You *may* try to replicate this kind of noise by using a known dataset (for example Urban sound), aggregating all the classes it has under the "non shang1" and train the classifier. Honestly, I don't know how well it will perform.

Of course, remember to 1) balance your dataset (since you will have many more samples of "negative" class than "shang1") or 2) properly set the class_weights parameter in random forest or 3) any other tecnique to handle imbalanced datasets.

Yes, you can reach me on Twitter. I warn you that I'm not always available though.

**Comment by pigener** [comment]
today I try again， a new compile error appears:
C:\Users\zhangkunyi\Desktop\arduinoSoundClassifier\main\main.ino: In function 'void loop()':
main:40:52: error: no matching function for call to 'Eloquent::ML::Port::RandomForest::predictLabel(double [32])'
     Serial.println(classifier.predictLabel(features));
                                                    ^
In file included from C:\Users\zhangkunyi\Desktop\arduinoSoundClassifier\main\main.ino:3:0:
C:\Users\zhangkunyi\Desktop\arduinoSoundClassifier\main\model.h:4361:33: note: candidate: const char* Eloquent::ML::Port::RandomForest::predictLabel(float*)
                     const char* predictLabel(float *x) {
                                 ^~~~~~~~~~~~
C:\Users\zhangkunyi\Desktop\arduinoSoundClassifier\main\model.h:4361:33: note:   no known conversion for argument 1 from 'double [32]' to 'float*'
**Is that because I change the NUM_SAMPLES const to 32 ?**

**Comment by pigener** [comment]
I modified the model.h file and it work! but the result is regret. I can't correctlly classify  even tow words :"shang" , "xia".   *o*  Orz...
